pipeline {
    agent any
    
    environment {
        NODE_VERSION = '16' // Define a versão do Node.js
        YARN_VERSION = '1.22.17' // Define a versão do Yarn
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    // Define o ambiente Node.js e Yarn
                    def nodeHome = tool 'NodeJS ' + NODE_VERSION
                    env.PATH = "${nodeHome}/bin:${env.PATH}"
                    def yarnHome = tool 'Yarn ' + YARN_VERSION
                    env.PATH = "${yarnHome}/bin:${env.PATH}"
                    
                    // Instala as dependências usando Yarn
                    sh 'yarn install'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    // Define o ambiente Node.js e Yarn novamente (pode ser necessário dependendo do ambiente)
                    def nodeHome = tool 'NodeJS ' + NODE_VERSION
                    env.PATH = "${nodeHome}/bin:${env.PATH}"
                    def yarnHome = tool 'Yarn ' + YARN_VERSION
                    env.PATH = "${yarnHome}/bin:${env.PATH}"
                    
                    // Executa o comando de build (substitua pelo seu comando de build específico)
                    sh 'yarn build'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    // Define o ambiente Node.js e Yarn novamente se necessário
                    
                    // Executa os testes (substitua pelo seu comando de teste específico)
                    sh 'yarn test'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // Define o ambiente Node.js e Yarn novamente se necessário
                    
                    // Executa o deploy (substitua pelo seu comando de deploy específico)
                    sh 'yarn start'
                }
            }
        }
    }
    
    post {
        always {
            // Limpa o ambiente após a execução do pipeline, se necessário
        }
    }
}