pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    // Instala as dependências usando Yarn
                    sh 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash'
                    sh 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \\. "$NVM_DIR/nvm.sh"'


                    sh 'source ~/.bashrc'
                    sh 'nvm use'
                    sh 'npm i'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    // Executa o comando de build (substitua pelo seu comando de build específico)
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // Define o ambiente Node.js e Yarn novamente se necessário
                    
                    // Executa o deploy (substitua pelo seu comando de deploy específico)
                    sh 'npm run start'
                }
            }
        }
    }
}