pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    // Instala as dependências usando Yarn
                    sh 'npm i'
                }
            }
        }
        
        stage('Build') {
            steps {
                script {
                    // Executa o comando de build (substitua pelo seu comando de build específico)
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // Define o ambiente Node.js e Yarn novamente se necessário
                    
                    // Executa o deploy (substitua pelo seu comando de deploy específico)
                    sh 'npm run start'
                }
            }
        }
    }
}